# Generated by Django 5.0.6 on 2025-02-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cse23_27',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_no', models.IntegerField()),
                ('register_number', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
    ]
